version: '3'
services:
  db:
    image: postgres:13.3
    restart: always
    container_name: db
    environment:
#      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5477:5432"  #коннект к БД порт - 5477 в appl.properties
  app:
    image: springboot-postgresql
    build: ./
    restart: always
    container_name: app
    ports:
      - "8088:8080"  #приложение поднимается на порту 8088 docker-compose up
    depends_on:
      - "db"