version: '3'
services:
  db:
    image: postgres:13.3
    restart: always
    container_name: db
    environment:
      - POSTGRES_DB=postgresn
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
#  app:
#    image: springboot-postgresql
#    build: ./
#    restart: always
#    container_name: app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - "db"